# Generated by Django 4.2.5 on 2023-10-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата изменения')),
                ('code', models.CharField(max_length=6, verbose_name='Код')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
